# Generated by Django 5.2.5 on 2025-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='posts_pics/default.png', upload_to='posts_pics'),
        ),
    ]
