# Generated by Django 5.2.5 on 2025-09-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'permissions': [('can_change_profile', 'Can change profile')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
