# Generated by Django 5.2.5 on 2025-08-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='image',
            field=models.ImageField(default='posts_pics/default.png', upload_to='posts_pics'),
        ),
    ]
